name: Check for broken links
on:
  pull_request:
    branches:
    - main
    - main-null-unsafe
  schedule:
  # Run the quality job at 4am every day
  - cron: '0 4 * * *'

jobs:
  link-check:
    runs-on: ubuntu-latest
    env:
      LYCHEE_OUT: tmp/lychee_results.md
    steps:
    - uses: actions/checkout@master
    - name: Check links
      id: check_links
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        # All of the globbing below
        args: >
          --config .github/workflows/link_check_config.lychee.toml
          **/*.md
          **/*.yaml
          **/*.dart
    # lychee-action doesn't fail outright — we need to do it ourselves.
    - name: Fail on broken links
      if: steps.check_links.outputs.exit_code != 0
      env:
        EXIT_CODE: ${{ steps.check_links.outputs.exit_code }}
      run: |
        cat $LYCHEE_OUT
        exit $EXIT_CODE
